

server:
  port: 8081
  max-http-header-size: 100000
    

spring:
  profiles:
    active:
    - stage 
  application:
    name: AUTHENTICATION_SERVICE
  mail:
    host: smtp.gmail.com
    port: 587
    username: tekbista375@gmail.com
    password: inleajnotmxzteeb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    
    
 
---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 
    username: 
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'false'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    activate:
      on-profile: prod
 

---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/shop24x7_stage
    username: root
    password: samuel545
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'false'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    activate:
      on-profile: qa


---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/shop24x7_stage
    username: root
    password: samuel545
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'false'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    activate:
      on-profile: preqa
  
---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/shop24x7_stage
    username: root
    password: samuel545
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    activate:
      on-profile: stage
  
      
  
security:
  jwt:
    token:
      secret-key: myjwtsecret
      expire-length: 3600000 
      
#eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: localhost
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka  

